#pragma once
#include "defs.h"

#include <array>

// Auto-generated by tools/generate_attacks.py — do not edit manually.

extern const std::array<U64, 64> BISHOP_MASKS;
extern const std::array<U64, 64> ROOK_MASKS;
extern const std::array<U64, 64> BISHOP_MAGIC_NUMBERS;
extern const std::array<U64, 64> ROOK_MAGIC_NUMBERS;
extern const std::array<int, 64> BISHOP_RELEVANT_BITS;
extern const std::array<int, 64> ROOK_RELEVANT_BITS;
extern const U64 BISHOP_ATTACKS[32768];
extern const U64 ROOK_ATTACKS[262144];

inline U64 bishop_attack_entry(int square, int index) {
    return BISHOP_ATTACKS[(square * 512) + index];
}

inline U64 rook_attack_entry(int square, int index) {
    return ROOK_ATTACKS[(square * 4096) + index];
}
